# Generated by Django 5.1 on 2024-08-29 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0002_remove_menu_link_new_tab_menu_link_nova_aba'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu_link',
            name='nova_aba',
        ),
        migrations.AddField(
            model_name='menu_link',
            name='new_tab',
            field=models.BooleanField(default=False),
        ),
    ]
