# Generated by Django 5.1.1 on 2024-09-12 17:11

import utils.models_validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0007_sitesetup_favicon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetup',
            name='favicon',
            field=models.ImageField(blank=True, default='', upload_to='assets/favicon/%Y/%M', validators=[utils.models_validator.validate_png]),
        ),
    ]
