# Generated by Django 5.1.1 on 2024-09-18 17:45

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_postattachment'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='post',
            managers=[
                ('obj', django.db.models.manager.Manager()),
            ],
        ),
    ]
